require("lze").load({
  { import = "custom.plugins.neotest" },

  { import = "custom.plugins.completion.cmp" },
  { import = "custom.plugins.completion.luasnip" },

  { import = "custom.plugins.lsp.lspconfig" },
  { import = "custom.plugins.lsp.lspsaga" },
  { import = "custom.plugins.lsp.tiny-inline-diagnostic" },
  { import = "custom.plugins.lsp.tsc" },

  { import = "custom.plugins.treesitter.treesitter" },
  { import = "custom.plugins.treesitter.autopairs" },
  { import = "custom.plugins.treesitter.rainbow-delimiters" },
  { import = "custom.plugins.treesitter.ts-comments" },
  { import = "custom.plugins.treesitter.vim-matchup" },
  { import = "custom.plugins.treesitter.vim-illuminate" },
  { import = "custom.plugins.treesitter.nvim-ts-autotag" },

  { import = "custom.plugins.persistence.persisted" },
  { import = "custom.plugins.persistence.auto-save" },
  { import = "custom.plugins.persistence.undotree" },

  { import = "custom.plugins.utils.legendary" },
  { import = "custom.plugins.utils.conform" },
  { import = "custom.plugins.utils.live-command" },
  { import = "custom.plugins.utils.grug-far" },
  { import = "custom.plugins.utils.scope" },
  { import = "custom.plugins.utils.dial" },
  { import = "custom.plugins.utils.nvim-surround" },
  { import = "custom.plugins.utils.toggleterm" },
  { import = "custom.plugins.utils.mini" },
  { import = "custom.plugins.utils.snacks" },
  { import = "custom.plugins.utils.gx" },
  { import = "custom.plugins.utils.vim-visual-multi" },
  { import = "custom.plugins.utils.hydra" },
  { import = "custom.plugins.utils.vim-caser" },
  { import = "custom.plugins.utils.sniprun" },
  { import = "custom.plugins.utils.code_runner" },
  { import = "custom.plugins.utils.nvim-recorder" },
  { import = "custom.plugins.utils.debugprint" },
  { import = "custom.plugins.utils.cutlass" },
  { import = "custom.plugins.utils.stay-in-place" },
  { import = "custom.plugins.utils.jq-playground" },

  { import = "custom.plugins.ui.bufferline" },
  { import = "custom.plugins.ui.comment-box" },
  { import = "custom.plugins.ui.nvim-notify" },
  { import = "custom.plugins.ui.helpview" },
  { import = "custom.plugins.ui.hlargs" },
  { import = "custom.plugins.ui.lualine" },
  { import = "custom.plugins.ui.neoscroll" },
  { import = "custom.plugins.ui.noice" },
  { import = "custom.plugins.ui.nvim-bqf" },
  { import = "custom.plugins.ui.nvim-scrollbar" },
  { import = "custom.plugins.ui.nvim-scrollview" },
  { import = "custom.plugins.ui.nvim-hlslens" },
  { import = "custom.plugins.ui.nvim-ufo" },
  { import = "custom.plugins.ui.marks" },
  { import = "custom.plugins.ui.registers" },
  { import = "custom.plugins.ui.todo-comments" },
  { import = "custom.plugins.ui.nvim-highlight-colors" },
  { import = "custom.plugins.ui.ccc" },
  { import = "custom.plugins.ui.incline" },
  { import = "custom.plugins.ui.reticle" },
  { import = "custom.plugins.ui.trouble" },
  { import = "custom.plugins.ui.dropbar" },

  { import = "custom.plugins.navigation.tmux" },
  { import = "custom.plugins.navigation.leap" },
  { import = "custom.plugins.navigation.flash" },
  { import = "custom.plugins.navigation.hop" },
  { import = "custom.plugins.navigation.nap" },

  { import = "custom.plugins.explorer.telescope" },
  { import = "custom.plugins.explorer.yazi" },
  { import = "custom.plugins.explorer.nvim-tree" },
  { import = "custom.plugins.explorer.nvim-tree-preview" },

  { import = "custom.plugins.ai.codecompanion" },
  { import = "custom.plugins.ai.avante" },

  { import = "custom.plugins.git.diffview" },
  { import = "custom.plugins.git.git-conflict" },
  { import = "custom.plugins.git.gitsigns" },
  { import = "custom.plugins.git.lazygit" },

  { import = "custom.plugins.filetypes.log-highlight" },
  { import = "custom.plugins.filetypes.kulala" },
  { import = "custom.plugins.filetypes.mkdnflow" },
  { import = "custom.plugins.filetypes.csvview" },
})
